# The Docker image that will be used to build your app
image: artifactory.cloud.statcan.ca/docker/cimg/node:current

pages:
  script:
    # Grab the GitLab Pages URL and strip out the domain, leaving only the path
    - NUXT_APP_BASE_URL=/`echo "$CI_PAGES_URL" | grep -oP 'https?://[^/]+/\K.*'`/
    - export NUXT_APP_BASE_URL
    # Nuxt Generate
    - npm install
    - npm run generate
    # Move the generated files to the /public directory of the project
    - rm -rf public
    - mkdir public
    - mv .output/public/* ./public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment: production
